### ISSUE TITLE
How to set the selected date on the datepicker

### ISSUE THREAD

**Issue by paulbryan** [jefelewis/react-native-ultimate-modal-picker#5]
Need a property to set the value of the datepicker

**Comment by paulbryan** [comment]
Also maybe a list of unselectable dates?

**Comment by jefelewis** [comment]
Hey Paul,

Thanks for the suggestion! I can implement a prop to  in the coming days. I've got a pretty busy the next few days, but I should be able to get it implemented by the end of the week.

As far as unselectable/blocked/disabled dates, I use the @react-native-community/datetimepicker library and it's based the native iOS [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker) and that doesn't allow you to disable specific dates.

You could possibly add something in with your state and if it lands on that date, you can send the user an alert, and then reset the state for the dat since it's a disabled date. Ideally, it would be best to not even give the user the option, but it's out of my control. The only other way would be to build a date picker module from scratch and that would be pretty time consuming.

**Comment by jefelewis** [comment]
Closing Issue.
